# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GenericInteract.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GenericInteract.proto',
  package='GenericInteractSpace',
  syntax='proto3',
  serialized_options=b'\n.org.eclipse.mosaic.fed.output.generator.zeromqB\025GenericInteractProtosH\003P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15GenericInteract.proto\x12\x14GenericInteractSpace\"\x95\x08\n\x0fGenericInteract\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x0f\n\x07type_id\x18\x04 \x01(\t\x12T\n\x10rsu_registration\x18\x05 \x01(\x0b\x32\x38.GenericInteractSpace.GenericInteract.RsuRegistrationBufH\x00\x12R\n\x0fvehicle_updates\x18\x06 \x01(\x0b\x32\x37.GenericInteractSpace.GenericInteract.VehicleUpdatesBufH\x00\x12\\\n\x14vehicle_registration\x18\x07 \x01(\x0b\x32<.GenericInteractSpace.GenericInteract.VehicleRegistrationBufH\x00\x12]\n\x15v2x_message_reception\x18\x08 \x01(\x0b\x32<.GenericInteractSpace.GenericInteract.V2xMessageReceptionBufH\x00\x1a\x34\n\x12RsuRegistrationBuf\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x03(\x01\x1a\x8a\x01\n\x0eVehicleDataBuf\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x03(\x01\x12\x0f\n\x07road_id\x18\x04 \x01(\t\x12\x10\n\x08route_id\x18\x05 \x01(\t\x12\r\n\x05speed\x18\x06 \x01(\x01\x12\x18\n\x10longitudinal_acc\x18\x07 \x01(\x01\x1a\xad\x01\n\x11VehicleUpdatesBuf\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x43\n\x05\x61\x64\x64\x65\x64\x18\x02 \x03(\x0b\x32\x34.GenericInteractSpace.GenericInteract.VehicleDataBuf\x12\x45\n\x07updated\x18\x03 \x03(\x0b\x32\x34.GenericInteractSpace.GenericInteract.VehicleDataBuf\x1aK\n\x16VehicleRegistrationBuf\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x14\n\x0c\x61pplications\x18\x03 \x03(\t\x1a\x8d\x01\n\x16V2xMessageReceptionBuf\x12\x15\n\rreceiver_name\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x03\x12\x11\n\tsend_time\x18\x03 \x01(\x03\x12\x14\n\x0creceive_time\x18\x04 \x01(\x03\x12\x1f\n\x17receive_signal_strength\x18\x05 \x01(\x01\x42\r\n\x0bInteractionBK\n.org.eclipse.mosaic.fed.output.generator.zeromqB\x15GenericInteractProtosH\x03P\x01\x62\x06proto3'
)




_GENERICINTERACT_RSUREGISTRATIONBUF = _descriptor.Descriptor(
  name='RsuRegistrationBuf',
  full_name='GenericInteractSpace.GenericInteract.RsuRegistrationBuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GenericInteractSpace.GenericInteract.RsuRegistrationBuf.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='GenericInteractSpace.GenericInteract.RsuRegistrationBuf.position', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=540,
)

_GENERICINTERACT_VEHICLEDATABUF = _descriptor.Descriptor(
  name='VehicleDataBuf',
  full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.position', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='road_id', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.road_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_id', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.route_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.speed', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitudinal_acc', full_name='GenericInteractSpace.GenericInteract.VehicleDataBuf.longitudinal_acc', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=681,
)

_GENERICINTERACT_VEHICLEUPDATESBUF = _descriptor.Descriptor(
  name='VehicleUpdatesBuf',
  full_name='GenericInteractSpace.GenericInteract.VehicleUpdatesBuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='GenericInteractSpace.GenericInteract.VehicleUpdatesBuf.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='added', full_name='GenericInteractSpace.GenericInteract.VehicleUpdatesBuf.added', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='GenericInteractSpace.GenericInteract.VehicleUpdatesBuf.updated', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=857,
)

_GENERICINTERACT_VEHICLEREGISTRATIONBUF = _descriptor.Descriptor(
  name='VehicleRegistrationBuf',
  full_name='GenericInteractSpace.GenericInteract.VehicleRegistrationBuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GenericInteractSpace.GenericInteract.VehicleRegistrationBuf.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group', full_name='GenericInteractSpace.GenericInteract.VehicleRegistrationBuf.group', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applications', full_name='GenericInteractSpace.GenericInteract.VehicleRegistrationBuf.applications', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=859,
  serialized_end=934,
)

_GENERICINTERACT_V2XMESSAGERECEPTIONBUF = _descriptor.Descriptor(
  name='V2xMessageReceptionBuf',
  full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver_name', full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf.receiver_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf.message_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_time', full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf.send_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receive_time', full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf.receive_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receive_signal_strength', full_name='GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf.receive_signal_strength', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=937,
  serialized_end=1078,
)

_GENERICINTERACT = _descriptor.Descriptor(
  name='GenericInteract',
  full_name='GenericInteractSpace.GenericInteract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='GenericInteractSpace.GenericInteract.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='GenericInteractSpace.GenericInteract.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='GenericInteractSpace.GenericInteract.sender_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='GenericInteractSpace.GenericInteract.type_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rsu_registration', full_name='GenericInteractSpace.GenericInteract.rsu_registration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle_updates', full_name='GenericInteractSpace.GenericInteract.vehicle_updates', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle_registration', full_name='GenericInteractSpace.GenericInteract.vehicle_registration', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v2x_message_reception', full_name='GenericInteractSpace.GenericInteract.v2x_message_reception', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GENERICINTERACT_RSUREGISTRATIONBUF, _GENERICINTERACT_VEHICLEDATABUF, _GENERICINTERACT_VEHICLEUPDATESBUF, _GENERICINTERACT_VEHICLEREGISTRATIONBUF, _GENERICINTERACT_V2XMESSAGERECEPTIONBUF, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Interaction', full_name='GenericInteractSpace.GenericInteract.Interaction',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=48,
  serialized_end=1093,
)

_GENERICINTERACT_RSUREGISTRATIONBUF.containing_type = _GENERICINTERACT
_GENERICINTERACT_VEHICLEDATABUF.containing_type = _GENERICINTERACT
_GENERICINTERACT_VEHICLEUPDATESBUF.fields_by_name['added'].message_type = _GENERICINTERACT_VEHICLEDATABUF
_GENERICINTERACT_VEHICLEUPDATESBUF.fields_by_name['updated'].message_type = _GENERICINTERACT_VEHICLEDATABUF
_GENERICINTERACT_VEHICLEUPDATESBUF.containing_type = _GENERICINTERACT
_GENERICINTERACT_VEHICLEREGISTRATIONBUF.containing_type = _GENERICINTERACT
_GENERICINTERACT_V2XMESSAGERECEPTIONBUF.containing_type = _GENERICINTERACT
_GENERICINTERACT.fields_by_name['rsu_registration'].message_type = _GENERICINTERACT_RSUREGISTRATIONBUF
_GENERICINTERACT.fields_by_name['vehicle_updates'].message_type = _GENERICINTERACT_VEHICLEUPDATESBUF
_GENERICINTERACT.fields_by_name['vehicle_registration'].message_type = _GENERICINTERACT_VEHICLEREGISTRATIONBUF
_GENERICINTERACT.fields_by_name['v2x_message_reception'].message_type = _GENERICINTERACT_V2XMESSAGERECEPTIONBUF
_GENERICINTERACT.oneofs_by_name['Interaction'].fields.append(
  _GENERICINTERACT.fields_by_name['rsu_registration'])
_GENERICINTERACT.fields_by_name['rsu_registration'].containing_oneof = _GENERICINTERACT.oneofs_by_name['Interaction']
_GENERICINTERACT.oneofs_by_name['Interaction'].fields.append(
  _GENERICINTERACT.fields_by_name['vehicle_updates'])
_GENERICINTERACT.fields_by_name['vehicle_updates'].containing_oneof = _GENERICINTERACT.oneofs_by_name['Interaction']
_GENERICINTERACT.oneofs_by_name['Interaction'].fields.append(
  _GENERICINTERACT.fields_by_name['vehicle_registration'])
_GENERICINTERACT.fields_by_name['vehicle_registration'].containing_oneof = _GENERICINTERACT.oneofs_by_name['Interaction']
_GENERICINTERACT.oneofs_by_name['Interaction'].fields.append(
  _GENERICINTERACT.fields_by_name['v2x_message_reception'])
_GENERICINTERACT.fields_by_name['v2x_message_reception'].containing_oneof = _GENERICINTERACT.oneofs_by_name['Interaction']
DESCRIPTOR.message_types_by_name['GenericInteract'] = _GENERICINTERACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericInteract = _reflection.GeneratedProtocolMessageType('GenericInteract', (_message.Message,), {

  'RsuRegistrationBuf' : _reflection.GeneratedProtocolMessageType('RsuRegistrationBuf', (_message.Message,), {
    'DESCRIPTOR' : _GENERICINTERACT_RSUREGISTRATIONBUF,
    '__module__' : 'GenericInteract_pb2'
    # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract.RsuRegistrationBuf)
    })
  ,

  'VehicleDataBuf' : _reflection.GeneratedProtocolMessageType('VehicleDataBuf', (_message.Message,), {
    'DESCRIPTOR' : _GENERICINTERACT_VEHICLEDATABUF,
    '__module__' : 'GenericInteract_pb2'
    # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract.VehicleDataBuf)
    })
  ,

  'VehicleUpdatesBuf' : _reflection.GeneratedProtocolMessageType('VehicleUpdatesBuf', (_message.Message,), {
    'DESCRIPTOR' : _GENERICINTERACT_VEHICLEUPDATESBUF,
    '__module__' : 'GenericInteract_pb2'
    # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract.VehicleUpdatesBuf)
    })
  ,

  'VehicleRegistrationBuf' : _reflection.GeneratedProtocolMessageType('VehicleRegistrationBuf', (_message.Message,), {
    'DESCRIPTOR' : _GENERICINTERACT_VEHICLEREGISTRATIONBUF,
    '__module__' : 'GenericInteract_pb2'
    # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract.VehicleRegistrationBuf)
    })
  ,

  'V2xMessageReceptionBuf' : _reflection.GeneratedProtocolMessageType('V2xMessageReceptionBuf', (_message.Message,), {
    'DESCRIPTOR' : _GENERICINTERACT_V2XMESSAGERECEPTIONBUF,
    '__module__' : 'GenericInteract_pb2'
    # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf)
    })
  ,
  'DESCRIPTOR' : _GENERICINTERACT,
  '__module__' : 'GenericInteract_pb2'
  # @@protoc_insertion_point(class_scope:GenericInteractSpace.GenericInteract)
  })
_sym_db.RegisterMessage(GenericInteract)
_sym_db.RegisterMessage(GenericInteract.RsuRegistrationBuf)
_sym_db.RegisterMessage(GenericInteract.VehicleDataBuf)
_sym_db.RegisterMessage(GenericInteract.VehicleUpdatesBuf)
_sym_db.RegisterMessage(GenericInteract.VehicleRegistrationBuf)
_sym_db.RegisterMessage(GenericInteract.V2xMessageReceptionBuf)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
