# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zeromq_interact.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zeromq_interact.proto',
  package='ZInteractSpace',
  syntax='proto3',
  serialized_options=b'\n.org.eclipse.mosaic.fed.output.generator.zeromqB\017ZInteractProtosH\003P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15zeromq_interact.proto\x12\x0eZInteractSpace\"\xb9\x07\n\tZInteract\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x0f\n\x07type_id\x18\x04 \x01(\t\x12H\n\x12z_rsu_registration\x18\x05 \x01(\x0b\x32*.ZInteractSpace.ZInteract.ZRsuRegistrationH\x00\x12\x46\n\x11z_vehicle_updates\x18\x06 \x01(\x0b\x32).ZInteractSpace.ZInteract.ZVehicleUpdatesH\x00\x12P\n\x16z_vehicle_registration\x18\x07 \x01(\x0b\x32..ZInteractSpace.ZInteract.ZVehicleRegistrationH\x00\x12Q\n\x17z_v2x_message_reception\x18\x08 \x01(\x0b\x32..ZInteractSpace.ZInteract.ZV2xMessageReceptionH\x00\x1a\x32\n\x10ZRsuRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x03(\x01\x1a\x88\x01\n\x0cZVehicleData\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x03(\x01\x12\x0f\n\x07road_id\x18\x04 \x01(\t\x12\x10\n\x08route_id\x18\x05 \x01(\t\x12\r\n\x05speed\x18\x06 \x01(\x01\x12\x18\n\x10longitudinal_acc\x18\x07 \x01(\x01\x1a\x8f\x01\n\x0fZVehicleUpdates\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x35\n\x05\x61\x64\x64\x65\x64\x18\x02 \x03(\x0b\x32&.ZInteractSpace.ZInteract.ZVehicleData\x12\x37\n\x07updated\x18\x03 \x03(\x0b\x32&.ZInteractSpace.ZInteract.ZVehicleData\x1aI\n\x14ZVehicleRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x14\n\x0c\x61pplications\x18\x03 \x03(\t\x1a\x8b\x01\n\x14ZV2xMessageReception\x12\x15\n\rreceiver_name\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x03\x12\x11\n\tsend_time\x18\x03 \x01(\x03\x12\x14\n\x0creceive_time\x18\x04 \x01(\x03\x12\x1f\n\x17receive_signal_strength\x18\x05 \x01(\x01\x42\r\n\x0bInteractionBE\n.org.eclipse.mosaic.fed.output.generator.zeromqB\x0fZInteractProtosH\x03P\x01\x62\x06proto3'
)




_ZINTERACT_ZRSUREGISTRATION = _descriptor.Descriptor(
  name='ZRsuRegistration',
  full_name='ZInteractSpace.ZInteract.ZRsuRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ZInteractSpace.ZInteract.ZRsuRegistration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='ZInteractSpace.ZInteract.ZRsuRegistration.position', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=478,
)

_ZINTERACT_ZVEHICLEDATA = _descriptor.Descriptor(
  name='ZVehicleData',
  full_name='ZInteractSpace.ZInteract.ZVehicleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ZInteractSpace.ZInteract.ZVehicleData.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ZInteractSpace.ZInteract.ZVehicleData.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='ZInteractSpace.ZInteract.ZVehicleData.position', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='road_id', full_name='ZInteractSpace.ZInteract.ZVehicleData.road_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_id', full_name='ZInteractSpace.ZInteract.ZVehicleData.route_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='ZInteractSpace.ZInteract.ZVehicleData.speed', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitudinal_acc', full_name='ZInteractSpace.ZInteract.ZVehicleData.longitudinal_acc', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=617,
)

_ZINTERACT_ZVEHICLEUPDATES = _descriptor.Descriptor(
  name='ZVehicleUpdates',
  full_name='ZInteractSpace.ZInteract.ZVehicleUpdates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ZInteractSpace.ZInteract.ZVehicleUpdates.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='added', full_name='ZInteractSpace.ZInteract.ZVehicleUpdates.added', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='ZInteractSpace.ZInteract.ZVehicleUpdates.updated', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=763,
)

_ZINTERACT_ZVEHICLEREGISTRATION = _descriptor.Descriptor(
  name='ZVehicleRegistration',
  full_name='ZInteractSpace.ZInteract.ZVehicleRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ZInteractSpace.ZInteract.ZVehicleRegistration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group', full_name='ZInteractSpace.ZInteract.ZVehicleRegistration.group', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applications', full_name='ZInteractSpace.ZInteract.ZVehicleRegistration.applications', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=838,
)

_ZINTERACT_ZV2XMESSAGERECEPTION = _descriptor.Descriptor(
  name='ZV2xMessageReception',
  full_name='ZInteractSpace.ZInteract.ZV2xMessageReception',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver_name', full_name='ZInteractSpace.ZInteract.ZV2xMessageReception.receiver_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='ZInteractSpace.ZInteract.ZV2xMessageReception.message_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_time', full_name='ZInteractSpace.ZInteract.ZV2xMessageReception.send_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receive_time', full_name='ZInteractSpace.ZInteract.ZV2xMessageReception.receive_time', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receive_signal_strength', full_name='ZInteractSpace.ZInteract.ZV2xMessageReception.receive_signal_strength', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=841,
  serialized_end=980,
)

_ZINTERACT = _descriptor.Descriptor(
  name='ZInteract',
  full_name='ZInteractSpace.ZInteract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ZInteractSpace.ZInteract.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='ZInteractSpace.ZInteract.id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='ZInteractSpace.ZInteract.sender_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type_id', full_name='ZInteractSpace.ZInteract.type_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_rsu_registration', full_name='ZInteractSpace.ZInteract.z_rsu_registration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_vehicle_updates', full_name='ZInteractSpace.ZInteract.z_vehicle_updates', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_vehicle_registration', full_name='ZInteractSpace.ZInteract.z_vehicle_registration', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_v2x_message_reception', full_name='ZInteractSpace.ZInteract.z_v2x_message_reception', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ZINTERACT_ZRSUREGISTRATION, _ZINTERACT_ZVEHICLEDATA, _ZINTERACT_ZVEHICLEUPDATES, _ZINTERACT_ZVEHICLEREGISTRATION, _ZINTERACT_ZV2XMESSAGERECEPTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Interaction', full_name='ZInteractSpace.ZInteract.Interaction',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=42,
  serialized_end=995,
)

_ZINTERACT_ZRSUREGISTRATION.containing_type = _ZINTERACT
_ZINTERACT_ZVEHICLEDATA.containing_type = _ZINTERACT
_ZINTERACT_ZVEHICLEUPDATES.fields_by_name['added'].message_type = _ZINTERACT_ZVEHICLEDATA
_ZINTERACT_ZVEHICLEUPDATES.fields_by_name['updated'].message_type = _ZINTERACT_ZVEHICLEDATA
_ZINTERACT_ZVEHICLEUPDATES.containing_type = _ZINTERACT
_ZINTERACT_ZVEHICLEREGISTRATION.containing_type = _ZINTERACT
_ZINTERACT_ZV2XMESSAGERECEPTION.containing_type = _ZINTERACT
_ZINTERACT.fields_by_name['z_rsu_registration'].message_type = _ZINTERACT_ZRSUREGISTRATION
_ZINTERACT.fields_by_name['z_vehicle_updates'].message_type = _ZINTERACT_ZVEHICLEUPDATES
_ZINTERACT.fields_by_name['z_vehicle_registration'].message_type = _ZINTERACT_ZVEHICLEREGISTRATION
_ZINTERACT.fields_by_name['z_v2x_message_reception'].message_type = _ZINTERACT_ZV2XMESSAGERECEPTION
_ZINTERACT.oneofs_by_name['Interaction'].fields.append(
  _ZINTERACT.fields_by_name['z_rsu_registration'])
_ZINTERACT.fields_by_name['z_rsu_registration'].containing_oneof = _ZINTERACT.oneofs_by_name['Interaction']
_ZINTERACT.oneofs_by_name['Interaction'].fields.append(
  _ZINTERACT.fields_by_name['z_vehicle_updates'])
_ZINTERACT.fields_by_name['z_vehicle_updates'].containing_oneof = _ZINTERACT.oneofs_by_name['Interaction']
_ZINTERACT.oneofs_by_name['Interaction'].fields.append(
  _ZINTERACT.fields_by_name['z_vehicle_registration'])
_ZINTERACT.fields_by_name['z_vehicle_registration'].containing_oneof = _ZINTERACT.oneofs_by_name['Interaction']
_ZINTERACT.oneofs_by_name['Interaction'].fields.append(
  _ZINTERACT.fields_by_name['z_v2x_message_reception'])
_ZINTERACT.fields_by_name['z_v2x_message_reception'].containing_oneof = _ZINTERACT.oneofs_by_name['Interaction']
DESCRIPTOR.message_types_by_name['ZInteract'] = _ZINTERACT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ZInteract = _reflection.GeneratedProtocolMessageType('ZInteract', (_message.Message,), {

  'ZRsuRegistration' : _reflection.GeneratedProtocolMessageType('ZRsuRegistration', (_message.Message,), {
    'DESCRIPTOR' : _ZINTERACT_ZRSUREGISTRATION,
    '__module__' : 'zeromq_interact_pb2'
    # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract.ZRsuRegistration)
    })
  ,

  'ZVehicleData' : _reflection.GeneratedProtocolMessageType('ZVehicleData', (_message.Message,), {
    'DESCRIPTOR' : _ZINTERACT_ZVEHICLEDATA,
    '__module__' : 'zeromq_interact_pb2'
    # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract.ZVehicleData)
    })
  ,

  'ZVehicleUpdates' : _reflection.GeneratedProtocolMessageType('ZVehicleUpdates', (_message.Message,), {
    'DESCRIPTOR' : _ZINTERACT_ZVEHICLEUPDATES,
    '__module__' : 'zeromq_interact_pb2'
    # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract.ZVehicleUpdates)
    })
  ,

  'ZVehicleRegistration' : _reflection.GeneratedProtocolMessageType('ZVehicleRegistration', (_message.Message,), {
    'DESCRIPTOR' : _ZINTERACT_ZVEHICLEREGISTRATION,
    '__module__' : 'zeromq_interact_pb2'
    # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract.ZVehicleRegistration)
    })
  ,

  'ZV2xMessageReception' : _reflection.GeneratedProtocolMessageType('ZV2xMessageReception', (_message.Message,), {
    'DESCRIPTOR' : _ZINTERACT_ZV2XMESSAGERECEPTION,
    '__module__' : 'zeromq_interact_pb2'
    # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract.ZV2xMessageReception)
    })
  ,
  'DESCRIPTOR' : _ZINTERACT,
  '__module__' : 'zeromq_interact_pb2'
  # @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteract)
  })
_sym_db.RegisterMessage(ZInteract)
_sym_db.RegisterMessage(ZInteract.ZRsuRegistration)
_sym_db.RegisterMessage(ZInteract.ZVehicleData)
_sym_db.RegisterMessage(ZInteract.ZVehicleUpdates)
_sym_db.RegisterMessage(ZInteract.ZVehicleRegistration)
_sym_db.RegisterMessage(ZInteract.ZV2xMessageReception)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
