// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

/**
 * Protobuf type {@code ZInteractSpace.ZInteractMinimal}
 */
public final class ZInteractMinimal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ZInteractSpace.ZInteractMinimal)
    ZInteractMinimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ZInteractMinimal.newBuilder() to construct.
  private ZInteractMinimal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZInteractMinimal() {
    senderId_ = "";
    typeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZInteractMinimal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ZInteractMinimal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            time_ = input.readInt64();
            break;
          }
          case 16: {

            id_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            senderId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            typeId_ = s;
            break;
          }
          case 42: {
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder subBuilder = null;
            if (vehicleUpdates_ != null) {
              subBuilder = vehicleUpdates_.toBuilder();
            }
            vehicleUpdates_ = input.readMessage(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vehicleUpdates_);
              vehicleUpdates_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZInteractMinimal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZInteractMinimal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.class, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.Builder.class);
  }

  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private long id_;
  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int SENDER_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object senderId_;
  /**
   * <code>string sender_id = 3;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public java.lang.String getSenderId() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderId_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_id = 3;</code>
   * @return The bytes for senderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderIdBytes() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object typeId_;
  /**
   * <code>string type_id = 4;</code>
   * @return The typeId.
   */
  @java.lang.Override
  public java.lang.String getTypeId() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeId_ = s;
      return s;
    }
  }
  /**
   * <code>string type_id = 4;</code>
   * @return The bytes for typeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeIdBytes() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_UPDATES_FIELD_NUMBER = 5;
  private org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal vehicleUpdates_;
  /**
   * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
   * @return Whether the vehicleUpdates field is set.
   */
  @java.lang.Override
  public boolean hasVehicleUpdates() {
    return vehicleUpdates_ != null;
  }
  /**
   * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
   * @return The vehicleUpdates.
   */
  @java.lang.Override
  public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal getVehicleUpdates() {
    return vehicleUpdates_ == null ? org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.getDefaultInstance() : vehicleUpdates_;
  }
  /**
   * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
   */
  @java.lang.Override
  public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimalOrBuilder getVehicleUpdatesOrBuilder() {
    return getVehicleUpdates();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (time_ != 0L) {
      output.writeInt64(1, time_);
    }
    if (id_ != 0L) {
      output.writeInt64(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(typeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, typeId_);
    }
    if (vehicleUpdates_ != null) {
      output.writeMessage(5, getVehicleUpdates());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(typeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, typeId_);
    }
    if (vehicleUpdates_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVehicleUpdates());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal)) {
      return super.equals(obj);
    }
    org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal other = (org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal) obj;

    if (getTime()
        != other.getTime()) return false;
    if (getId()
        != other.getId()) return false;
    if (!getSenderId()
        .equals(other.getSenderId())) return false;
    if (!getTypeId()
        .equals(other.getTypeId())) return false;
    if (hasVehicleUpdates() != other.hasVehicleUpdates()) return false;
    if (hasVehicleUpdates()) {
      if (!getVehicleUpdates()
          .equals(other.getVehicleUpdates())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId().hashCode();
    hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTypeId().hashCode();
    if (hasVehicleUpdates()) {
      hash = (37 * hash) + VEHICLE_UPDATES_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleUpdates().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ZInteractSpace.ZInteractMinimal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ZInteractSpace.ZInteractMinimal)
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZInteractMinimal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZInteractMinimal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.class, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.Builder.class);
    }

    // Construct using org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      time_ = 0L;

      id_ = 0L;

      senderId_ = "";

      typeId_ = "";

      if (vehicleUpdatesBuilder_ == null) {
        vehicleUpdates_ = null;
      } else {
        vehicleUpdates_ = null;
        vehicleUpdatesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZInteractMinimal_descriptor;
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal getDefaultInstanceForType() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.getDefaultInstance();
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal build() {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal buildPartial() {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal result = new org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal(this);
      result.time_ = time_;
      result.id_ = id_;
      result.senderId_ = senderId_;
      result.typeId_ = typeId_;
      if (vehicleUpdatesBuilder_ == null) {
        result.vehicleUpdates_ = vehicleUpdates_;
      } else {
        result.vehicleUpdates_ = vehicleUpdatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal) {
        return mergeFrom((org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal other) {
      if (other == org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal.getDefaultInstance()) return this;
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getSenderId().isEmpty()) {
        senderId_ = other.senderId_;
        onChanged();
      }
      if (!other.getTypeId().isEmpty()) {
        typeId_ = other.typeId_;
        onChanged();
      }
      if (other.hasVehicleUpdates()) {
        mergeVehicleUpdates(other.getVehicleUpdates());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long time_ ;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 1;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object senderId_ = "";
    /**
     * <code>string sender_id = 3;</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_id = 3;</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_id = 3;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_id = 3;</code>
     * @param value The bytes for senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeId_ = "";
    /**
     * <code>string type_id = 4;</code>
     * @return The typeId.
     */
    public java.lang.String getTypeId() {
      java.lang.Object ref = typeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_id = 4;</code>
     * @return The bytes for typeId.
     */
    public com.google.protobuf.ByteString
        getTypeIdBytes() {
      java.lang.Object ref = typeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_id = 4;</code>
     * @param value The typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeId() {
      
      typeId_ = getDefaultInstance().getTypeId();
      onChanged();
      return this;
    }
    /**
     * <code>string type_id = 4;</code>
     * @param value The bytes for typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeId_ = value;
      onChanged();
      return this;
    }

    private org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal vehicleUpdates_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimalOrBuilder> vehicleUpdatesBuilder_;
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     * @return Whether the vehicleUpdates field is set.
     */
    public boolean hasVehicleUpdates() {
      return vehicleUpdatesBuilder_ != null || vehicleUpdates_ != null;
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     * @return The vehicleUpdates.
     */
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal getVehicleUpdates() {
      if (vehicleUpdatesBuilder_ == null) {
        return vehicleUpdates_ == null ? org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.getDefaultInstance() : vehicleUpdates_;
      } else {
        return vehicleUpdatesBuilder_.getMessage();
      }
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public Builder setVehicleUpdates(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal value) {
      if (vehicleUpdatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vehicleUpdates_ = value;
        onChanged();
      } else {
        vehicleUpdatesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public Builder setVehicleUpdates(
        org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder builderForValue) {
      if (vehicleUpdatesBuilder_ == null) {
        vehicleUpdates_ = builderForValue.build();
        onChanged();
      } else {
        vehicleUpdatesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public Builder mergeVehicleUpdates(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal value) {
      if (vehicleUpdatesBuilder_ == null) {
        if (vehicleUpdates_ != null) {
          vehicleUpdates_ =
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.newBuilder(vehicleUpdates_).mergeFrom(value).buildPartial();
        } else {
          vehicleUpdates_ = value;
        }
        onChanged();
      } else {
        vehicleUpdatesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public Builder clearVehicleUpdates() {
      if (vehicleUpdatesBuilder_ == null) {
        vehicleUpdates_ = null;
        onChanged();
      } else {
        vehicleUpdates_ = null;
        vehicleUpdatesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder getVehicleUpdatesBuilder() {
      
      onChanged();
      return getVehicleUpdatesFieldBuilder().getBuilder();
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimalOrBuilder getVehicleUpdatesOrBuilder() {
      if (vehicleUpdatesBuilder_ != null) {
        return vehicleUpdatesBuilder_.getMessageOrBuilder();
      } else {
        return vehicleUpdates_ == null ?
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.getDefaultInstance() : vehicleUpdates_;
      }
    }
    /**
     * <code>.ZInteractSpace.ZVehicleUpdatesMinimal vehicle_updates = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimalOrBuilder> 
        getVehicleUpdatesFieldBuilder() {
      if (vehicleUpdatesBuilder_ == null) {
        vehicleUpdatesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimal.Builder, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleUpdatesMinimalOrBuilder>(
                getVehicleUpdates(),
                getParentForChildren(),
                isClean());
        vehicleUpdates_ = null;
      }
      return vehicleUpdatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ZInteractSpace.ZInteractMinimal)
  }

  // @@protoc_insertion_point(class_scope:ZInteractSpace.ZInteractMinimal)
  private static final org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal();
  }

  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ZInteractMinimal>
      PARSER = new com.google.protobuf.AbstractParser<ZInteractMinimal>() {
    @java.lang.Override
    public ZInteractMinimal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ZInteractMinimal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ZInteractMinimal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZInteractMinimal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractMinimal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

