// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

public final class ZInteractProtos {
  private ZInteractProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteractMinimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteractMinimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZVehicleDataMinimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZVehicleUpdatesMinimal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZVehicleUpdatesMinimal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_ZRsuRegistration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_ZRsuRegistration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_ZVehicleData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_ZVehicleData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_ZVehicleUpdates_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_ZVehicleUpdates_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_ZVehicleRegistration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_ZVehicleRegistration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ZInteractSpace_ZInteract_ZV2xMessageReception_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ZInteractSpace_ZInteract_ZV2xMessageReception_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025zeromq_interact.proto\022\016ZInteractSpace\"" +
      "\221\001\n\020ZInteractMinimal\022\014\n\004time\030\001 \001(\003\022\n\n\002id" +
      "\030\002 \001(\003\022\021\n\tsender_id\030\003 \001(\t\022\017\n\007type_id\030\004 \001" +
      "(\t\022?\n\017vehicle_updates\030\005 \001(\0132&.ZInteractS" +
      "pace.ZVehicleUpdatesMinimal\"\201\001\n\023ZVehicle" +
      "DataMinimal\022\014\n\004name\030\001 \001(\t\022\020\n\010position\030\002 " +
      "\003(\001\022\017\n\007road_id\030\003 \001(\t\022\020\n\010route_id\030\004 \001(\t\022\r" +
      "\n\005speed\030\005 \001(\001\022\030\n\020longitudinal_acc\030\006 \001(\001\"" +
      "N\n\026ZVehicleUpdatesMinimal\0224\n\007updated\030\001 \003" +
      "(\0132#.ZInteractSpace.ZVehicleDataMinimal\"" +
      "\276\007\n\tZInteract\022\014\n\004time\030\001 \001(\003\022\n\n\002id\030\002 \001(\003\022" +
      "\021\n\tsender_id\030\003 \001(\t\022\017\n\007type_id\030\004 \001(\t\022H\n\022z" +
      "_rsu_registration\030\005 \001(\0132*.ZInteractSpace" +
      ".ZInteract.ZRsuRegistrationH\000\022F\n\021z_vehic" +
      "le_updates\030\006 \001(\0132).ZInteractSpace.ZInter" +
      "act.ZVehicleUpdatesH\000\022P\n\026z_vehicle_regis" +
      "tration\030\007 \001(\0132..ZInteractSpace.ZInteract" +
      ".ZVehicleRegistrationH\000\022Q\n\027z_v2x_message" +
      "_reception\030\010 \001(\0132..ZInteractSpace.ZInter" +
      "act.ZV2xMessageReceptionH\000\0322\n\020ZRsuRegist" +
      "ration\022\014\n\004name\030\001 \001(\t\022\020\n\010position\030\002 \003(\001\032\210" +
      "\001\n\014ZVehicleData\022\014\n\004time\030\001 \001(\003\022\014\n\004name\030\002 " +
      "\001(\t\022\020\n\010position\030\003 \003(\001\022\017\n\007road_id\030\004 \001(\t\022\020" +
      "\n\010route_id\030\005 \001(\t\022\r\n\005speed\030\006 \001(\001\022\030\n\020longi" +
      "tudinal_acc\030\007 \001(\001\032\217\001\n\017ZVehicleUpdates\022\014\n" +
      "\004time\030\001 \001(\003\0225\n\005added\030\002 \003(\0132&.ZInteractSp" +
      "ace.ZInteract.ZVehicleData\0227\n\007updated\030\003 " +
      "\003(\0132&.ZInteractSpace.ZInteract.ZVehicleD" +
      "ata\032I\n\024ZVehicleRegistration\022\014\n\004name\030\001 \001(" +
      "\t\022\r\n\005group\030\002 \001(\t\022\024\n\014applications\030\003 \003(\t\032\213" +
      "\001\n\024ZV2xMessageReception\022\025\n\rreceiver_name" +
      "\030\001 \001(\t\022\022\n\nmessage_id\030\002 \001(\003\022\021\n\tsend_time\030" +
      "\003 \001(\003\022\024\n\014receive_time\030\004 \001(\003\022\037\n\027receive_s" +
      "ignal_strength\030\005 \001(\001B\022\n\020interaction_type" +
      "BM\n8org.eclipse.mosaic.fed.output.genera" +
      "tor.zeromq.zprotobufB\017ZInteractProtosP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ZInteractSpace_ZInteractMinimal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ZInteractSpace_ZInteractMinimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteractMinimal_descriptor,
        new java.lang.String[] { "Time", "Id", "SenderId", "TypeId", "VehicleUpdates", });
    internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ZInteractSpace_ZVehicleDataMinimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor,
        new java.lang.String[] { "Name", "Position", "RoadId", "RouteId", "Speed", "LongitudinalAcc", });
    internal_static_ZInteractSpace_ZVehicleUpdatesMinimal_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ZInteractSpace_ZVehicleUpdatesMinimal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZVehicleUpdatesMinimal_descriptor,
        new java.lang.String[] { "Updated", });
    internal_static_ZInteractSpace_ZInteract_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ZInteractSpace_ZInteract_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_descriptor,
        new java.lang.String[] { "Time", "Id", "SenderId", "TypeId", "ZRsuRegistration", "ZVehicleUpdates", "ZVehicleRegistration", "ZV2XMessageReception", "InteractionType", });
    internal_static_ZInteractSpace_ZInteract_ZRsuRegistration_descriptor =
      internal_static_ZInteractSpace_ZInteract_descriptor.getNestedTypes().get(0);
    internal_static_ZInteractSpace_ZInteract_ZRsuRegistration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_ZRsuRegistration_descriptor,
        new java.lang.String[] { "Name", "Position", });
    internal_static_ZInteractSpace_ZInteract_ZVehicleData_descriptor =
      internal_static_ZInteractSpace_ZInteract_descriptor.getNestedTypes().get(1);
    internal_static_ZInteractSpace_ZInteract_ZVehicleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_ZVehicleData_descriptor,
        new java.lang.String[] { "Time", "Name", "Position", "RoadId", "RouteId", "Speed", "LongitudinalAcc", });
    internal_static_ZInteractSpace_ZInteract_ZVehicleUpdates_descriptor =
      internal_static_ZInteractSpace_ZInteract_descriptor.getNestedTypes().get(2);
    internal_static_ZInteractSpace_ZInteract_ZVehicleUpdates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_ZVehicleUpdates_descriptor,
        new java.lang.String[] { "Time", "Added", "Updated", });
    internal_static_ZInteractSpace_ZInteract_ZVehicleRegistration_descriptor =
      internal_static_ZInteractSpace_ZInteract_descriptor.getNestedTypes().get(3);
    internal_static_ZInteractSpace_ZInteract_ZVehicleRegistration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_ZVehicleRegistration_descriptor,
        new java.lang.String[] { "Name", "Group", "Applications", });
    internal_static_ZInteractSpace_ZInteract_ZV2xMessageReception_descriptor =
      internal_static_ZInteractSpace_ZInteract_descriptor.getNestedTypes().get(4);
    internal_static_ZInteractSpace_ZInteract_ZV2xMessageReception_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ZInteractSpace_ZInteract_ZV2xMessageReception_descriptor,
        new java.lang.String[] { "ReceiverName", "MessageId", "SendTime", "ReceiveTime", "ReceiveSignalStrength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
