// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

public interface ZInteractOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZInteractSpace.ZInteract)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string sender_id = 3;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 3;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string type_id = 4;</code>
   * @return The typeId.
   */
  java.lang.String getTypeId();
  /**
   * <code>string type_id = 4;</code>
   * @return The bytes for typeId.
   */
  com.google.protobuf.ByteString
      getTypeIdBytes();

  /**
   * <code>.ZInteractSpace.ZInteract.ZRsuRegistration z_rsu_registration = 5;</code>
   * @return Whether the zRsuRegistration field is set.
   */
  boolean hasZRsuRegistration();
  /**
   * <code>.ZInteractSpace.ZInteract.ZRsuRegistration z_rsu_registration = 5;</code>
   * @return The zRsuRegistration.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteract.ZRsuRegistration getZRsuRegistration();

  /**
   * <code>.ZInteractSpace.ZInteract.ZVehicleUpdates z_vehicle_updates = 6;</code>
   * @return Whether the zVehicleUpdates field is set.
   */
  boolean hasZVehicleUpdates();
  /**
   * <code>.ZInteractSpace.ZInteract.ZVehicleUpdates z_vehicle_updates = 6;</code>
   * @return The zVehicleUpdates.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteract.ZVehicleUpdates getZVehicleUpdates();

  /**
   * <code>.ZInteractSpace.ZInteract.ZVehicleRegistration z_vehicle_registration = 7;</code>
   * @return Whether the zVehicleRegistration field is set.
   */
  boolean hasZVehicleRegistration();
  /**
   * <code>.ZInteractSpace.ZInteract.ZVehicleRegistration z_vehicle_registration = 7;</code>
   * @return The zVehicleRegistration.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteract.ZVehicleRegistration getZVehicleRegistration();

  /**
   * <code>.ZInteractSpace.ZInteract.ZV2xMessageReception z_v2x_message_reception = 8;</code>
   * @return Whether the zV2xMessageReception field is set.
   */
  boolean hasZV2XMessageReception();
  /**
   * <code>.ZInteractSpace.ZInteract.ZV2xMessageReception z_v2x_message_reception = 8;</code>
   * @return The zV2xMessageReception.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteract.ZV2xMessageReception getZV2XMessageReception();

  public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteract.InteractionCase getInteractionCase();
}
