// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

public interface ZVehicleDataMinimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZInteractSpace.ZVehicleDataMinimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated double position = 2;</code>
   * @return A list containing the position.
   */
  java.util.List<java.lang.Double> getPositionList();
  /**
   * <code>repeated double position = 2;</code>
   * @return The count of position.
   */
  int getPositionCount();
  /**
   * <code>repeated double position = 2;</code>
   * @param index The index of the element to return.
   * @return The position at the given index.
   */
  double getPosition(int index);

  /**
   * <pre>
   * IRoadPosition start
   *IRoadPosition IConnnection start
   * </pre>
   *
   * <code>string road_id = 3;</code>
   * @return The roadId.
   */
  java.lang.String getRoadId();
  /**
   * <pre>
   * IRoadPosition start
   *IRoadPosition IConnnection start
   * </pre>
   *
   * <code>string road_id = 3;</code>
   * @return The bytes for roadId.
   */
  com.google.protobuf.ByteString
      getRoadIdBytes();

  /**
   * <pre>
   * IRoadPosition IConnnection end
   * IRoadPosition end
   * </pre>
   *
   * <code>string route_id = 4;</code>
   * @return The routeId.
   */
  java.lang.String getRouteId();
  /**
   * <pre>
   * IRoadPosition IConnnection end
   * IRoadPosition end
   * </pre>
   *
   * <code>string route_id = 4;</code>
   * @return The bytes for routeId.
   */
  com.google.protobuf.ByteString
      getRouteIdBytes();

  /**
   * <code>double speed = 5;</code>
   * @return The speed.
   */
  double getSpeed();

  /**
   * <code>double longitudinal_acc = 6;</code>
   * @return The longitudinalAcc.
   */
  double getLongitudinalAcc();
}
