// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

/**
 * Protobuf type {@code ZInteractSpace.ZVehicleDataMinimal}
 */
public final class ZVehicleDataMinimal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ZInteractSpace.ZVehicleDataMinimal)
    ZVehicleDataMinimalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ZVehicleDataMinimal.newBuilder() to construct.
  private ZVehicleDataMinimal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ZVehicleDataMinimal() {
    name_ = "";
    position_ = emptyDoubleList();
    roadId_ = "";
    routeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ZVehicleDataMinimal();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ZVehicleDataMinimal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 17: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              position_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            position_.addDouble(input.readDouble());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              position_ = newDoubleList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              position_.addDouble(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            roadId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            routeId_ = s;
            break;
          }
          case 41: {

            speed_ = input.readDouble();
            break;
          }
          case 49: {

            longitudinalAcc_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        position_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZVehicleDataMinimal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.class, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.DoubleList position_;
  /**
   * <code>repeated double position = 2;</code>
   * @return A list containing the position.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getPositionList() {
    return position_;
  }
  /**
   * <code>repeated double position = 2;</code>
   * @return The count of position.
   */
  public int getPositionCount() {
    return position_.size();
  }
  /**
   * <code>repeated double position = 2;</code>
   * @param index The index of the element to return.
   * @return The position at the given index.
   */
  public double getPosition(int index) {
    return position_.getDouble(index);
  }
  private int positionMemoizedSerializedSize = -1;

  public static final int ROAD_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object roadId_;
  /**
   * <pre>
   * IRoadPosition start
   *IRoadPosition IConnnection start
   * </pre>
   *
   * <code>string road_id = 3;</code>
   * @return The roadId.
   */
  @java.lang.Override
  public java.lang.String getRoadId() {
    java.lang.Object ref = roadId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roadId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * IRoadPosition start
   *IRoadPosition IConnnection start
   * </pre>
   *
   * <code>string road_id = 3;</code>
   * @return The bytes for roadId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoadIdBytes() {
    java.lang.Object ref = roadId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roadId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object routeId_;
  /**
   * <pre>
   * IRoadPosition IConnnection end
   * IRoadPosition end
   * </pre>
   *
   * <code>string route_id = 4;</code>
   * @return The routeId.
   */
  @java.lang.Override
  public java.lang.String getRouteId() {
    java.lang.Object ref = routeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * IRoadPosition IConnnection end
   * IRoadPosition end
   * </pre>
   *
   * <code>string route_id = 4;</code>
   * @return The bytes for routeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRouteIdBytes() {
    java.lang.Object ref = routeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEED_FIELD_NUMBER = 5;
  private double speed_;
  /**
   * <code>double speed = 5;</code>
   * @return The speed.
   */
  @java.lang.Override
  public double getSpeed() {
    return speed_;
  }

  public static final int LONGITUDINAL_ACC_FIELD_NUMBER = 6;
  private double longitudinalAcc_;
  /**
   * <code>double longitudinal_acc = 6;</code>
   * @return The longitudinalAcc.
   */
  @java.lang.Override
  public double getLongitudinalAcc() {
    return longitudinalAcc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (getPositionList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(positionMemoizedSerializedSize);
    }
    for (int i = 0; i < position_.size(); i++) {
      output.writeDoubleNoTag(position_.getDouble(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roadId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roadId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(routeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, routeId_);
    }
    if (speed_ != 0D) {
      output.writeDouble(5, speed_);
    }
    if (longitudinalAcc_ != 0D) {
      output.writeDouble(6, longitudinalAcc_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getPositionList().size();
      size += dataSize;
      if (!getPositionList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      positionMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roadId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roadId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(routeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, routeId_);
    }
    if (speed_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, speed_);
    }
    if (longitudinalAcc_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, longitudinalAcc_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal)) {
      return super.equals(obj);
    }
    org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal other = (org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getPositionList()
        .equals(other.getPositionList())) return false;
    if (!getRoadId()
        .equals(other.getRoadId())) return false;
    if (!getRouteId()
        .equals(other.getRouteId())) return false;
    if (java.lang.Double.doubleToLongBits(getSpeed())
        != java.lang.Double.doubleToLongBits(
            other.getSpeed())) return false;
    if (java.lang.Double.doubleToLongBits(getLongitudinalAcc())
        != java.lang.Double.doubleToLongBits(
            other.getLongitudinalAcc())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getPositionCount() > 0) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPositionList().hashCode();
    }
    hash = (37 * hash) + ROAD_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRoadId().hashCode();
    hash = (37 * hash) + ROUTE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRouteId().hashCode();
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSpeed()));
    hash = (37 * hash) + LONGITUDINAL_ACC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLongitudinalAcc()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ZInteractSpace.ZVehicleDataMinimal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ZInteractSpace.ZVehicleDataMinimal)
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZVehicleDataMinimal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.class, org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.Builder.class);
    }

    // Construct using org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      position_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      roadId_ = "";

      routeId_ = "";

      speed_ = 0D;

      longitudinalAcc_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZInteractProtos.internal_static_ZInteractSpace_ZVehicleDataMinimal_descriptor;
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal getDefaultInstanceForType() {
      return org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.getDefaultInstance();
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal build() {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal buildPartial() {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal result = new org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000001) != 0)) {
        position_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.position_ = position_;
      result.roadId_ = roadId_;
      result.routeId_ = routeId_;
      result.speed_ = speed_;
      result.longitudinalAcc_ = longitudinalAcc_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal) {
        return mergeFrom((org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal other) {
      if (other == org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.position_.isEmpty()) {
        if (position_.isEmpty()) {
          position_ = other.position_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePositionIsMutable();
          position_.addAll(other.position_);
        }
        onChanged();
      }
      if (!other.getRoadId().isEmpty()) {
        roadId_ = other.roadId_;
        onChanged();
      }
      if (!other.getRouteId().isEmpty()) {
        routeId_ = other.routeId_;
        onChanged();
      }
      if (other.getSpeed() != 0D) {
        setSpeed(other.getSpeed());
      }
      if (other.getLongitudinalAcc() != 0D) {
        setLongitudinalAcc(other.getLongitudinalAcc());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.DoubleList position_ = emptyDoubleList();
    private void ensurePositionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        position_ = mutableCopy(position_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated double position = 2;</code>
     * @return A list containing the position.
     */
    public java.util.List<java.lang.Double>
        getPositionList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(position_) : position_;
    }
    /**
     * <code>repeated double position = 2;</code>
     * @return The count of position.
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated double position = 2;</code>
     * @param index The index of the element to return.
     * @return The position at the given index.
     */
    public double getPosition(int index) {
      return position_.getDouble(index);
    }
    /**
     * <code>repeated double position = 2;</code>
     * @param index The index to set the value at.
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(
        int index, double value) {
      ensurePositionIsMutable();
      position_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double position = 2;</code>
     * @param value The position to add.
     * @return This builder for chaining.
     */
    public Builder addPosition(double value) {
      ensurePositionIsMutable();
      position_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double position = 2;</code>
     * @param values The position to add.
     * @return This builder for chaining.
     */
    public Builder addAllPosition(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensurePositionIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, position_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double position = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {
      position_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.lang.Object roadId_ = "";
    /**
     * <pre>
     * IRoadPosition start
     *IRoadPosition IConnnection start
     * </pre>
     *
     * <code>string road_id = 3;</code>
     * @return The roadId.
     */
    public java.lang.String getRoadId() {
      java.lang.Object ref = roadId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roadId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * IRoadPosition start
     *IRoadPosition IConnnection start
     * </pre>
     *
     * <code>string road_id = 3;</code>
     * @return The bytes for roadId.
     */
    public com.google.protobuf.ByteString
        getRoadIdBytes() {
      java.lang.Object ref = roadId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roadId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * IRoadPosition start
     *IRoadPosition IConnnection start
     * </pre>
     *
     * <code>string road_id = 3;</code>
     * @param value The roadId to set.
     * @return This builder for chaining.
     */
    public Builder setRoadId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roadId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IRoadPosition start
     *IRoadPosition IConnnection start
     * </pre>
     *
     * <code>string road_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoadId() {
      
      roadId_ = getDefaultInstance().getRoadId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IRoadPosition start
     *IRoadPosition IConnnection start
     * </pre>
     *
     * <code>string road_id = 3;</code>
     * @param value The bytes for roadId to set.
     * @return This builder for chaining.
     */
    public Builder setRoadIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roadId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object routeId_ = "";
    /**
     * <pre>
     * IRoadPosition IConnnection end
     * IRoadPosition end
     * </pre>
     *
     * <code>string route_id = 4;</code>
     * @return The routeId.
     */
    public java.lang.String getRouteId() {
      java.lang.Object ref = routeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * IRoadPosition IConnnection end
     * IRoadPosition end
     * </pre>
     *
     * <code>string route_id = 4;</code>
     * @return The bytes for routeId.
     */
    public com.google.protobuf.ByteString
        getRouteIdBytes() {
      java.lang.Object ref = routeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * IRoadPosition IConnnection end
     * IRoadPosition end
     * </pre>
     *
     * <code>string route_id = 4;</code>
     * @param value The routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      routeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IRoadPosition IConnnection end
     * IRoadPosition end
     * </pre>
     *
     * <code>string route_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRouteId() {
      
      routeId_ = getDefaultInstance().getRouteId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IRoadPosition IConnnection end
     * IRoadPosition end
     * </pre>
     *
     * <code>string route_id = 4;</code>
     * @param value The bytes for routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      routeId_ = value;
      onChanged();
      return this;
    }

    private double speed_ ;
    /**
     * <code>double speed = 5;</code>
     * @return The speed.
     */
    @java.lang.Override
    public double getSpeed() {
      return speed_;
    }
    /**
     * <code>double speed = 5;</code>
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    public Builder setSpeed(double value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double speed = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeed() {
      
      speed_ = 0D;
      onChanged();
      return this;
    }

    private double longitudinalAcc_ ;
    /**
     * <code>double longitudinal_acc = 6;</code>
     * @return The longitudinalAcc.
     */
    @java.lang.Override
    public double getLongitudinalAcc() {
      return longitudinalAcc_;
    }
    /**
     * <code>double longitudinal_acc = 6;</code>
     * @param value The longitudinalAcc to set.
     * @return This builder for chaining.
     */
    public Builder setLongitudinalAcc(double value) {
      
      longitudinalAcc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double longitudinal_acc = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongitudinalAcc() {
      
      longitudinalAcc_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ZInteractSpace.ZVehicleDataMinimal)
  }

  // @@protoc_insertion_point(class_scope:ZInteractSpace.ZVehicleDataMinimal)
  private static final org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal();
  }

  public static org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ZVehicleDataMinimal>
      PARSER = new com.google.protobuf.AbstractParser<ZVehicleDataMinimal>() {
    @java.lang.Override
    public ZVehicleDataMinimal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ZVehicleDataMinimal(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ZVehicleDataMinimal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ZVehicleDataMinimal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

