// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zeromq_interact.proto

package org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf;

public interface ZVehicleUpdatesMinimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ZInteractSpace.ZVehicleUpdatesMinimal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ZInteractSpace.ZVehicleDataMinimal updated = 1;</code>
   */
  java.util.List<org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal> 
      getUpdatedList();
  /**
   * <code>repeated .ZInteractSpace.ZVehicleDataMinimal updated = 1;</code>
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimal getUpdated(int index);
  /**
   * <code>repeated .ZInteractSpace.ZVehicleDataMinimal updated = 1;</code>
   */
  int getUpdatedCount();
  /**
   * <code>repeated .ZInteractSpace.ZVehicleDataMinimal updated = 1;</code>
   */
  java.util.List<? extends org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimalOrBuilder> 
      getUpdatedOrBuilderList();
  /**
   * <code>repeated .ZInteractSpace.ZVehicleDataMinimal updated = 1;</code>
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.zprotobuf.ZVehicleDataMinimalOrBuilder getUpdatedOrBuilder(
      int index);
}
