// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenericInteract.proto

package org.eclipse.mosaic.fed.output.generator.zeromq;

public interface GenericInteractOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GenericInteractSpace.GenericInteract)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string sender_id = 3;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 3;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string type_id = 4;</code>
   * @return The typeId.
   */
  java.lang.String getTypeId();
  /**
   * <code>string type_id = 4;</code>
   * @return The bytes for typeId.
   */
  com.google.protobuf.ByteString
      getTypeIdBytes();

  /**
   * <code>.GenericInteractSpace.GenericInteract.RsuRegistrationBuf rsu_registration = 5;</code>
   * @return Whether the rsuRegistration field is set.
   */
  boolean hasRsuRegistration();
  /**
   * <code>.GenericInteractSpace.GenericInteract.RsuRegistrationBuf rsu_registration = 5;</code>
   * @return The rsuRegistration.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.GenericInteract.RsuRegistrationBuf getRsuRegistration();

  /**
   * <code>.GenericInteractSpace.GenericInteract.VehicleUpdatesBuf vehicle_updates = 6;</code>
   * @return Whether the vehicleUpdates field is set.
   */
  boolean hasVehicleUpdates();
  /**
   * <code>.GenericInteractSpace.GenericInteract.VehicleUpdatesBuf vehicle_updates = 6;</code>
   * @return The vehicleUpdates.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.GenericInteract.VehicleUpdatesBuf getVehicleUpdates();

  /**
   * <code>.GenericInteractSpace.GenericInteract.VehicleRegistrationBuf vehicle_registration = 7;</code>
   * @return Whether the vehicleRegistration field is set.
   */
  boolean hasVehicleRegistration();
  /**
   * <code>.GenericInteractSpace.GenericInteract.VehicleRegistrationBuf vehicle_registration = 7;</code>
   * @return The vehicleRegistration.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.GenericInteract.VehicleRegistrationBuf getVehicleRegistration();

  /**
   * <code>.GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf v2x_message_reception = 8;</code>
   * @return Whether the v2xMessageReception field is set.
   */
  boolean hasV2XMessageReception();
  /**
   * <code>.GenericInteractSpace.GenericInteract.V2xMessageReceptionBuf v2x_message_reception = 8;</code>
   * @return The v2xMessageReception.
   */
  org.eclipse.mosaic.fed.output.generator.zeromq.GenericInteract.V2xMessageReceptionBuf getV2XMessageReception();

  public org.eclipse.mosaic.fed.output.generator.zeromq.GenericInteract.InteractionCase getInteractionCase();
}
