// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GenericInteract.proto

package org.eclipse.mosaic.fed.output.generator.zeromq;

public final class GenericInteractProtos {
  private GenericInteractProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
